[2023-07-02T00:00:17.588+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-07-02T00:00:17.707+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-07-02T00:00:17.721+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-02T00:00:18.193+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): inaccurate> on 2023-07-01 00:00:00+00:00
[2023-07-02T00:00:18.310+0000] {standard_task_runner.py:57} INFO - Started process 413 to run task
[2023-07-02T00:00:18.388+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2023-07-01T00:00:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmphbupg3_6']
[2023-07-02T00:00:18.436+0000] {standard_task_runner.py:85} INFO - Job 183: Subtask inaccurate
[2023-07-02T00:00:20.164+0000] {task_command.py:410} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2023-07-01T00:00:00+00:00 [running]> on host 414be138234a
[2023-07-02T00:00:21.901+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2023-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-01T00:00:00+00:00'
[2023-07-02T00:00:21.915+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-02T00:00:21.918+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo inaccurate']
[2023-07-02T00:00:22.142+0000] {subprocess.py:86} INFO - Output:
[2023-07-02T00:00:22.152+0000] {subprocess.py:93} INFO - inaccurate
[2023-07-02T00:00:22.155+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-02T00:00:22.330+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20230701T000000, start_date=20230702T000017, end_date=20230702T000022
[2023-07-02T00:00:22.479+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-02T00:00:22.575+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
