[2023-06-27T01:45:20.867+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: search_posts.get_posts scheduled__2023-06-26T00:00:00+00:00 [queued]>
[2023-06-27T01:45:21.042+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: search_posts.get_posts scheduled__2023-06-26T00:00:00+00:00 [queued]>
[2023-06-27T01:45:21.058+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-27T01:45:22.476+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_posts> on 2023-06-26 00:00:00+00:00
[2023-06-27T01:45:23.032+0000] {standard_task_runner.py:57} INFO - Started process 204 to run task
[2023-06-27T01:45:23.294+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'search_posts', 'get_posts', 'scheduled__2023-06-26T00:00:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/search_posts.py', '--cfg-path', '/tmp/tmppn8t9c03']
[2023-06-27T01:45:23.338+0000] {standard_task_runner.py:85} INFO - Job 69: Subtask get_posts
[2023-06-27T01:45:26.074+0000] {task_command.py:410} INFO - Running <TaskInstance: search_posts.get_posts scheduled__2023-06-26T00:00:00+00:00 [running]> on host 414be138234a
[2023-06-27T01:45:31.220+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='search_posts' AIRFLOW_CTX_TASK_ID='get_posts' AIRFLOW_CTX_EXECUTION_DATE='2023-06-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-26T00:00:00+00:00'
[2023-06-27T01:45:31.241+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/search_posts.py", line 27, in get_posts
    reddit.connect_reddit(pickle_name = 'monkey')
  File "/opt/airflow/dags/lib/reddit_api.py", line 41, in connect_reddit
    self.your_pickle = pickle.load(open(pickle_name+'.pkl','rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'monkey.pkl'
[2023-06-27T01:45:31.610+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=search_posts, task_id=get_posts, execution_date=20230626T000000, start_date=20230627T014520, end_date=20230627T014531
[2023-06-27T01:45:31.829+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 69 for task get_posts ([Errno 2] No such file or directory: 'monkey.pkl'; 204)
[2023-06-27T01:45:32.145+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-27T01:45:32.364+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
