[2023-06-26T01:48:47.629+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2023-06-26T01:48:05.186200+00:00 [queued]>
[2023-06-26T01:48:47.706+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2023-06-26T01:48:05.186200+00:00 [queued]>
[2023-06-26T01:48:47.712+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-26T01:48:48.258+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): inaccurate> on 2023-06-26 01:48:05.186200+00:00
[2023-06-26T01:48:48.606+0000] {standard_task_runner.py:57} INFO - Started process 273 to run task
[2023-06-26T01:48:48.861+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2023-06-26T01:48:05.186200+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpg5p1s1bg']
[2023-06-26T01:48:48.887+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask inaccurate
[2023-06-26T01:48:52.488+0000] {task_command.py:410} INFO - Running <TaskInstance: my_dag.inaccurate manual__2023-06-26T01:48:05.186200+00:00 [running]> on host 414be138234a
[2023-06-26T01:48:59.597+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2023-06-26T01:48:05.186200+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-26T01:48:05.186200+00:00'
[2023-06-26T01:48:59.636+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-06-26T01:48:59.649+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo inaccurate']
[2023-06-26T01:48:59.966+0000] {subprocess.py:86} INFO - Output:
[2023-06-26T01:49:00.091+0000] {subprocess.py:93} INFO - inaccurate
[2023-06-26T01:49:00.127+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-26T01:49:01.369+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20230626T014805, start_date=20230626T014847, end_date=20230626T014901
[2023-06-26T01:49:02.556+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-26T01:49:04.169+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
